version: 2
root-markers:
  - .git/
lint-debound: ls

tools:
  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  rustfmt: &rustfmt
    format-command: 'rustfmt'
    format-stdin: true

languages:
  python:
    - <<: *python-black

  rust:
    - <<: *rustfmt
